Homework1 completed
sid1980/MikhailLitvinov pull request #1
Opened 2021-04-26 21:40 UTC by sid1980

Сделал 1 задание

2021-04-28 17:43 UTC, shoggy requested changes
Small typos: subtract, expected

2021-04-28 17:43 UTC, shoggy commented on src/test/java/ru/training/at/hw1/CalculatorAddOperationUnitTest.java
> +    }
Could you please move it to a separate class that contains only data providers (it can be one class for all four providers)?

2021-04-28 17:43 UTC, shoggy commented on src/test/java/ru/training/at/hw1/CalculatorAddOperationUnitTest.java
> +    public void testAddLong(long v1, long v2, long result)  {
Consider the use of more clear variables names (here and in other classes)
```suggestion
    public void testAddLong(long v1, long v2, long expected)  {
```

2021-04-28 17:43 UTC, shoggy commented on src/test/java/ru/training/at/hw1/CalculatorDivideOperationUnitTest.java
> +                //TODO: make method that check rule x/0 and get exception
It's a good point, please implement it

2021-05-03 18:57 UTC, sid1980 commented on pom.xml
> +    <artifactId>epam-test-auto-spring-2021</artifactId>
Hi, I can change ru.training.at to com.epam, but i think that used auther name in artifactId is bad idia ... what do you think about standart artifactId like "epam-test-auto-project", It is not duplicate information about in when are we study this cource,  but it is clean explanations about project. What do you think?

2021-05-03 20:05 UTC, sid1980 commented on src/test/java/ru/training/at/hw1/CalculatorAddOperationUnitTest.java
> +    public void testAddLong(long v1, long v2, long result)  {
fix it, and remove some unusefull code

2021-05-03 20:06 UTC, sid1980 commented on src/test/java/ru/training/at/hw1/CalculatorAddOperationUnitTest.java
> +    }
Fix it, move all invoke data providers in one class, and connect it with tests

2021-05-03 20:07 UTC, sid1980 commented on pom.xml
> +            <systemPath>${project.basedir}/src/main/resources/calculator-1.0.jar</systemPath>
Fix it, run console and run command mvn install

2021-05-03 20:11 UTC, sid1980 commented on src/test/java/ru/training/at/hw1/CalculatorDivideOperationUnitTest.java
> +                //TODO: make method that check rule x/0 and get exception
Add new method that expectedException and check it message,

2021-05-04 09:41 UTC, shoggy commented on pom.xml
> +    <artifactId>epam-test-auto-spring-2021</artifactId>
Good argumentation

2021-05-04 09:59 UTC, shoggy requested changes
You create a Calculator instance implicitly, the general approach is to use `@Before...` methods.
The second point: all four test classes will have the same `@Before...` method. This method should be moved to the parent class.
Please make appropriate changes. 
Do not forget to manually verify your solution, because some before-methods require specific parameter 

Could you please update typo-errors
subtruct -> subtract 
excepted -> expected

You can find usages by pressing `Ctrl+Shift+F`
![image](https://user-images.githubusercontent.com/13015572/116987482-ca7bf700-acd7-11eb-94a4-55a1948e1c4e.png)

2021-05-04 09:59 UTC, shoggy commented on pom.xml
> +            <systemPath>${project.basedir}/src/main/resources/calculator-1.0.jar</systemPath>
Looks like you read the documentation 👍 
Here I see two options:
1. `dependency>scope: system` -- you should provide `dependency>systemPath` and the referenced jar should be accessible (in our case it should be added to the git repository)
2. `mvn install` -- scope should not be `system`, no need to define `dependency>systemPath` because it confuses the reader

Please choose one of these

2021-05-04 09:59 UTC, shoggy commented on pom.xml
> +                <testng.suite.file>${project.build.testOutputDirectory}/addSubtructGrp.xml</testng.suite.file>
Please update property according to new file name

2021-05-04 19:44 UTC, sid1980 commented on pom.xml
> +            <systemPath>${project.basedir}/src/main/resources/calculator-1.0.jar</systemPath>
add calculator-1.0.jar to git repository

2021-05-04 19:45 UTC, sid1980 commented on pom.xml
> +                <testng.suite.file>${project.build.testOutputDirectory}/addSubtructGrp.xml</testng.suite.file>
rename and fix typo-errors

2021-05-04 19:47 UTC, sid1980 commented
- add instractions @BeforeClass and @AfterClass
- rename groupId and artifactId
- fix some typo-errors
- add calculator.jar to git repository

2021-05-05 11:25 UTC, sid1980 commented
- add AbstractCalculatorTest class 
- remove unused line of code

2021-05-05 11:34 UTC, shoggy approved these changes

2021-05-05 11:55 UTC, merged