Hw2
sid1980/MikhailLitvinov pull request #2
Opened 2021-05-09 23:00 UTC by sid1980

made HW2 (part1 and part2 )

2021-05-09 23:45 UTC, shoggy requested changes
Comments are applicable for both test classes

2021-05-09 23:45 UTC, shoggy commented on pom.xml
> +        </dependency>
Task requires to use TestNG

2021-05-09 23:45 UTC, shoggy commented on pom.xml
> +            <version>4.4.1</version>
Please move the version to the `properties` section

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/AbstractWebPageTest.java
> +    }
This is bad practice. 
Assume mmAssert contains some failures. 
The `@Test` annotated method is finished and is marked as Passed (because no AssertionError is thrown). 
`@After` method is executing and raises AssertionError

So test has wrong pass status

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +                .implicitlyWait(2, TimeUnit.SECONDS);
I think these statements should be in `@Before` method

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +        webDriver().findElement(By.xpath("//a[@href='#']")).click();
This reference is too common to be used. Please consider change to something more specific

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +        webDriver().manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
What for implicitlyWait param is updated here and why here?

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +                                "METALS & COLORS");
Please find elements by a more general way, not by href

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +                            .findElements(By.xpath("//div[@class='benefit-icon']")).size(),
Bys' priority:
1. DOM (id, name)
2. CSS 
3. XPATH

```suggestion
                            .findElements(By.css("div.benefit-icon")).size(),
```

2021-05-09 23:45 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +                                "Left Section: Home not found. ");
Please use more common way, that return `List<WebElements>` and remember about locator priorities

2021-05-10 12:34 UTC, shoggy commented on src/test/java/com/epam/hw2/AbstractWebPageTest.java
> +    }
For clarity, you can add comments and rename the getter
But this is test-method specific action (some methods use SoftAssert, some use regular Assert), so pushing to use it in all methods can lead to such difficulties

2021-05-10 21:06 UTC, sid1980 commented
- change topMenu and leftMenu now I made selector more complex and use cssSelector
  and check asserts with loop 
- change some xpath selectors to css
- change algorithm finding iframe

2021-05-12 10:10 UTC, shoggy requested changes

2021-05-12 10:10 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +        ArrayList menuPart01 = new ArrayList<>();
Please parameterize Lists
```suggestion
        ArrayList<String> menuPart01 = new ArrayList<>();
```

\+ in other places too

2021-05-12 10:10 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +                                "Texts are not displayed");
Here you need to check not only count but also texts itself

2021-05-12 10:10 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +        asert().assertTrue(isExistFrame, "iframe with “Frame Button” is not exist");
if `iframe#frame` is not last in the list, then `isExistFrame` will be false
You can use a different locator and check only not the emptiness of returned list

2021-05-12 10:10 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseFirst.java
> +        if (webDriver().getPageSource().contains("frame")) {
Here source text of the last loaded page is taken and the presence of the "frame" substring is checked
Would be better if you use another strategy for this

2021-05-12 10:10 UTC, shoggy commented on src/test/java/com/epam/hw2/ExerciseSecond.java
> +        webDriver().findElement(By.xpath("//a[@href='#']")).click();
Please make same change as in the first exercise

2021-05-16 15:42 UTC, sid1980 commented
- add benefit assert
- change iframe finding now by id
- fix ArrayList<String>

2021-05-17 18:11 UTC, shoggy approved these changes

2021-05-17 22:10 UTC, merged