Hw3
sid1980/MikhailLitvinov pull request #3
Opened 2021-05-11 00:09 UTC by sid1980

Made hw3 - made refactor to page object 
I will try realize flex and layered architecture, but for starting I made simple page object as I understend it. 
 It is cool stuff and I find bug in hw2, when made hw3 )) 
(One comment about loging was not chenging in second test (( unique methods for HomePage solved this error )

2021-05-11 22:41 UTC, sid1980 commented
- add class Driver 
- add class for loading property, tests are  working with chrome and firefox
- add some @FindBy  and By instructions in the begining of the class
- clean up some java code

2021-05-12 20:45 UTC, shoggy requested changes
Please put tests, pageobjects, driver and ConfReader in separate packages

Comments show examples of issues, please fix them in other places too

2021-05-12 20:45 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/DiffElementsPage.java
> +    private By checkboxBy = By.xpath("//div[@class='checkbox-row']//*//input[@type='checkbox']");
Please explain why not `@FindBy WebElement`?

2021-05-12 20:45 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/Driver.java
> +    static WebDriver driver;
In the case of parallel test execution, this will cause problems.
Please remove this variable and return new instance on each `getDriver()` call

2021-05-12 20:45 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/Driver.java
> +
Please get rid of this part and custom driver since you use WebDriverManager

2021-05-12 20:45 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/ExerciseFirst.java
> +                                                     "SERVICE", "METALS & COLORS");
You take some properties from external config, but some values are hardcoded. Please externalize such values too

2021-05-16 17:07 UTC, sid1980 commented
- add lists to property,
- fix singleton Driver
- remove unused code
- use FindBy for List of elements and By for single element

2021-05-16 17:11 UTC, sid1980 commented on src/test/java/com/epam/hw3/pageobject/DiffElementsPage.java
> +    private By checkboxBy = By.xpath("//div[@class='checkbox-row']//*//input[@type='checkbox']");
In side selenium documentation where are  lot of examples with By.  some thing, as for me a little bit simpler
one line By whan 2 line FindBy and  function for getter ... but now i think that if I have one element I try to use By and if I get List of elements I use FindBy

2021-05-17 17:57 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/Driver.java
> +    static WebDriver driver;
Using singleton for driver storage and managing is not a good idea.
Please do not store it here. Only `getDriver()` method should stay in this class

2021-05-17 18:04 UTC, shoggy requested changes
Please put tests, pageobjects, driver and ConfReader in separate packages

2021-05-17 18:04 UTC, shoggy commented on src/test/java/com/epam/hw3/pageobject/ExerciseFirst.java
> +        asert().assertEquals(homePage.getBenefitTxt(), 4, "Texts are not displayed");
`4` s look like test data, please move it to `.properties`

2021-05-17 18:04 UTC, shoggy commented on configuration.properties
> +browser               = chrome
move this file under `resources` directory

2021-05-18 05:37 UTC, sid1980 commented on configuration.properties
> +browser               = chrome
I have  quastion about test data, 
what is the preferred way to split  test data by files?
for example: 
every page object assign unique property file, 
all test case in one file or enything else

2021-05-18 06:42 UTC, shoggy commented on configuration.properties
> +browser               = chrome
In this case one file is enough. Pay attention for the fact that test data is part of a test, not of descriptive element (page object)

2021-05-20 23:32 UTC, sid1980 commented
- move tests, pageobjects, driver and ConfReader in separate packages
-  create components
- move test data to property 
- for about Driver (I add synchronized word for WebDriver it is for mulththreading and volatile for disable optimisation

2021-05-21 10:45 UTC, shoggy approved these changes
By separate package I ment something like `com.epam.hw3.pageobject`, `com.epam.hw3.driver`

2021-05-21 20:46 UTC, merged